### PR TITLE
fix(cluster-upgrade): added ability to upgrade unsupported versions

### LINKED ISSUE #193: [BUG] mksClusterV1 can't upgrade to unsupported version
While trying upgrade cluster from 1.17 to 1.18 got an error:
`Error: error updating cluster 'A1F4CF91-CF58-4BEE-98F2-8250E8C110D2': the cluster is already on the latest available minor version: 1.17`

### PR DESCRIPTION
**Pull request by TawR1024**
This PR will resolve  #193 

Changes:
Added ability to upgrade cluster to unsupported version. It make sense for users which have old clusters.

### CODE REVIEW

File: selectel/mks.go [hunk 1]
```diff
@@ -199,10 +199,61 @@ func mksClusterV1GetLatestPatchVersions(ctx context.Context, client *v1.ServiceC
 	return result, nil
 }
 
+func mksClusterV1GetLatestMinorVersion(ctx context.Context, client *v1.ServiceClient) (string, error) {
+	kubeVersions, _, err := kubeversion.List(ctx, client)
+	if err != nil {
+		return "", err
+	}
+
+	versions := map[string]struct{}{}
```
Comment (kolsean) [inline selectel/mks.go:208]: It seems that we can use `parseMKSKubeVersionsV1Latest` function here instead, because it does the same stuff

File: selectel/mks.go [hunk 2]
```diff
@@ -199,10 +199,61 @@ func mksClusterV1GetLatestPatchVersions(ctx context.Context, client *v1.ServiceC
...
+
+	return latestSupported, nil
+}
+
+// checkVersionIsSupported check that desired k8s version is supported.
+func checkVersionIsSupported(ctx context.Context, client *v1.ServiceClient, desiredMinorVersion string) (bool, error) {
+	kubeVersions, _, err := kubeversion.List(ctx, client)
+	if err != nil {
+		return false, err
+	}
```
Comment (kolsean) [inline selectel/mks.go:234]: It will be better if we will get `kubeVersions` list one time before and then pass this list to the function.
Also this way helps to add more simple unit tests.
For example, check `parseMKSKubeVersionsV1Latest` implementation.

File: selectel/mks.go [hunk 3]
```diff
@@ -199,10 +199,61 @@ func mksClusterV1GetLatestPatchVersions(ctx context.Context, client *v1.ServiceC
...
+
+	versions := map[string]struct{}{}
+	for _, version := range kubeVersions {
+		ver, err := kubeVersionTrimToMinor(version.Version)
+		if err != nil {
+			return false, fmt.Errorf("can't get minor version")
```
Comment (kolsean) [inline selectel/mks.go:240]: We have to pass `version.Version` here for better understanding or use `errors.New` function instead `fmt.Errorf`

File: selectel/mks.go [hunk 4]
```diff
@@ -238,25 +289,28 @@ func upgradeMKSClusterV1KubeVersion(ctx context.Context, d *schema.ResourceData,
...
+		}
 
-		// Compare the latest patch version with the desired version.
-		if desiredVersion != latestVersion {
-			return fmt.Errorf(
-				"current version %s can't be upgraded to version %s, the latest available version is: %s",
-				currentVersion, desiredVersion, latestVersion)
+		if latestMinorVersion == currentMinor {
+			return fmt.Errorf("the cluster is already on the latest available minor version: %s", currentMinor)
 		}
```
Comment (kolsean) [inline selectel/mks.go:314]: It seems that we can do this check earlier at 283 line after this code:
```
if desiredMinor != currentMinor {
		log.Print("[DEBUG] upgrading minor version")
```

**Review by kolsean — CHANGES_REQUESTED** [review]

File: selectel/mks.go (hunk 1 above)
Comment (TawR1024) [reply selectel/mks.go]: Ok, i agree, this method is unnecessary. Also I have added doc string for  `parseMKSKubeVersionsV1Latest` to make it more obvious.

File: selectel/mks.go (hunk 4 above)
Comment (TawR1024) [reply selectel/mks.go]: moved

File: selectel/mks.go [hunk 5]
```diff
@@ -283,34 +260,34 @@ func upgradeMKSClusterV1KubeVersion(ctx context.Context, d *schema.ResourceData,
...
-		}
-
-		latestMinorVersion, err := mksClusterV1GetLatestMinorVersion(ctx, client)
-		if err != nil {
-			return fmt.Errorf("can't find latest minor version: %s", err)
-		}
-
-		if latestMinorVersion == currentMinor {
-			return fmt.Errorf("the cluster is already on the latest available minor version: %s", currentMinor)
+			log.Print("[INFO] cluster will be upgrade to unsupported version. Patch version will be selected automatically.")
```
Comment (kolsean) [inline selectel/mks.go:290]: Maybe it will be better if we say `to unsupported minor version`?

File: go.mod [hunk 6]
```diff
@@ -5,6 +5,7 @@ go 1.17
 require (
 	github.com/hashicorp/go-retryablehttp v0.6.6
 	github.com/hashicorp/terraform-plugin-sdk/v2 v2.10.1
+	github.com/pkg/errors v0.9.1
```
Comment (kolsean) [inline go.mod:8]: let's use this package from stdlib

File: selectel/mks.go [hunk 7]
```diff
@@ -154,6 +155,9 @@ func mksClusterV1KubeVersionDiffSuppressFunc(k, old, new string, d *schema.Resou
 		return false
 	}
 	desiredPatch, err := kubeVersionToPatch(new)
+	if desiredPatch == 0 && desiredMinor == currentMinor {
```
Comment (kolsean) [inline selectel/mks.go:158]: I think we don't need to check `desiredMinor == currentMinor` here, because we've already checked cases when `desiredMinor > currentMinor` and `desiredMinor < currentMinor` earlier.
On the other hand, if we have an error in the result of  `kubeVersionToPatch(new)`, desiredPatch int value will be always equal to zero, so we don't need to check it too.
To simplify this case we can just return `true` in case of `err != nil` below.

**Review by kolsean — CHANGES_REQUESTED** [review]

File: selectel/mks.go (hunk 7 above)
Comment (TawR1024) [reply selectel/mks.go]: Yep, it make sense to simplify this check.

**Review by kolsean — APPROVED** [review]
LGTM! 👍
